baseURL = 'https://yodg.netlify.app/'
locale = 'en-us'
title = 'yodg'
theme = 'hugo-theme-console'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  person = 'people'

[params]
  description = "Hello world!"
  animateStyle = "animate-fade-up" # Animation style for content

[[params.navlinks]]
  name = "me/"
  url = "/about/"

[[params.navlinks]]
  name = "srch/"
  url = "/search/"

[[params.navlinks]]
  name = "posts/"
  url = "/posts/"

[[params.navlinks]]
  name = "med/"
  url = "/media/"

[[params.navlinks]]
  name = "ppl/"
  url = "/people/"
