backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "content"
public_folder: "/"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          default: "{{now}}",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "books"
    label: "Books"
    folder: "content/media/books"
    create: true
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "book" }
      - {
          label: "Type",
          name: "type",
          widget: "hidden",
          default: "encyclopedia",
        }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Author", name: "people", widget: "list", allow_add: true }
      - { label: "Series", name: "series", widget: "string" }
      - { label: "Description", name: "description", widget: "richtext" }
      - { label: "Publisher", name: "publisher", widget: "string" }
      - { label: "Publication Date", name: "published", widget: "datetime" }
      - { label: "ISBN", name: "isbn", widget: "string" }
      - { label: "Genres", name: "categories", widget: "list", allow_add: true }
      - {
          label: "Subgenres & Tropes",
          name: "tags",
          widget: "list",
          allow_add: true,
        }
      - {
          label: "Started Reading",
          name: "started",
          widget: "datetime",
          required: false,
        }
      - {
          label: "Finished Reading",
          name: "finished",
          widget: "datetime",
          required: false,
        }
      - {
          label: "Rating",
          name: "rating",
          widget: "number",
          min: 0,
          max: 5,
          step: 0.5,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
